### ISSUE TITLE
[Feature Request] Configurable base directory

### ISSUE THREAD

**Issue by tehbilly** [0xB4LINT/nginxconfig.io#64]
On my laptop I'd like to use `/usr/local/var/www` as the root directory. Currently I have to download the configuration and replace all `/var` with `/usr/local/var` before I can use it. Would be nice to not have to go through that step.

Totally low priority issue, but thought it might be helpful!

**Comment by valentinxxx** [comment]
There is a `Path` option where you can define the `/usr/local/var/www` directory.
Or is your issue related to Let's Encrypt's base directory (`/var/www/_letsencrypt`)?

**Comment by tehbilly** [comment]
More the second, that all of the directories I have to edit to have that prefix. if I am using homebrew then I'd be looking in `/usr/local/...`, or macports would be `/opt/local/...` for essentially all of the paths there.

I've actually made changes in my fork that would accomplish this, although the UI changes leave a little to be desired _(that's why I haven't opened a pull request)_. I don't terribly mind as this is a rather niche situation, but at least wanted to bring it up in case others have the same issue.
